/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedGovernanceRouteImport } from './routes/_authenticated/governance'
import { Route as AuthenticatedOperationsRouteImport } from './routes/_authenticated/operations'
import { Route as AuthenticatedParticipantsRouteImport } from './routes/_authenticated/participants'
import { Route as AuthenticatedQuantumLabRouteImport } from './routes/_authenticated/quantum-lab'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedAboutRouteImport } from './routes/_protected/about'
import { Route as ProtectedGenomicsRouteImport } from './routes/_protected/genomics'
import { Route as ProtectedPlatformRouteImport } from './routes/_protected/platform'
import { Route as ProtectedResearchRouteImport } from './routes/_protected/research'
import { Route as ProtectedSecurityRouteImport } from './routes/_protected/security'
import { Route as AuthenticatedCandidatesCandidateIdRouteImport } from './routes/_authenticated/candidates.$candidateId'
import { Route as AuthenticatedStudiesIndexRouteImport } from './routes/_authenticated/studies.index'
import { Route as AuthenticatedStudiesStudyIdRouteImport } from './routes/_authenticated/studies.$studyId'
import { Route as ProtectedDiseasesIndexRouteImport } from './routes/_protected/diseases.index'
import { Route as ProtectedDiseasesSlugRouteImport } from './routes/_protected/diseases.$slug'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGovernanceRoute = AuthenticatedGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperationsRoute = AuthenticatedOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParticipantsRoute =
  AuthenticatedParticipantsRouteImport.update({
    id: '/participants',
    path: '/participants',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuantumLabRoute = AuthenticatedQuantumLabRouteImport.update({
  id: '/quantum-lab',
  path: '/quantum-lab',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/_protected/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAboutRoute = ProtectedAboutRouteImport.update({
  id: '/_protected/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedGenomicsRoute = ProtectedGenomicsRouteImport.update({
  id: '/_protected/genomics',
  path: '/genomics',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPlatformRoute = ProtectedPlatformRouteImport.update({
  id: '/_protected/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedResearchRoute = ProtectedResearchRouteImport.update({
  id: '/_protected/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSecurityRoute = ProtectedSecurityRouteImport.update({
  id: '/_protected/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCandidatesCandidateIdRoute =
  AuthenticatedCandidatesCandidateIdRouteImport.update({
    id: '/candidates/$candidateId',
    path: '/candidates/$candidateId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudiesIndexRoute =
  AuthenticatedStudiesIndexRouteImport.update({
    id: '/studies/',
    path: '/studies/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudiesStudyIdRoute =
  AuthenticatedStudiesStudyIdRouteImport.update({
    id: '/studies/$studyId',
    path: '/studies/$studyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ProtectedDiseasesIndexRoute = ProtectedDiseasesIndexRouteImport.update({
  id: '/_protected/diseases/',
  path: '/diseases/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDiseasesSlugRoute = ProtectedDiseasesSlugRouteImport.update({
  id: '/_protected/diseases/$slug',
  path: '/diseases/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/governance': typeof AuthenticatedGovernanceRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/participants': typeof AuthenticatedParticipantsRoute
  '/quantum-lab': typeof AuthenticatedQuantumLabRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/about': typeof ProtectedAboutRoute
  '/genomics': typeof ProtectedGenomicsRoute
  '/platform': typeof ProtectedPlatformRoute
  '/research': typeof ProtectedResearchRoute
  '/security': typeof ProtectedSecurityRoute
  '/candidates/$candidateId': typeof AuthenticatedCandidatesCandidateIdRoute
  '/studies/$studyId': typeof AuthenticatedStudiesStudyIdRoute
  '/diseases/$slug': typeof ProtectedDiseasesSlugRoute
  '/studies/': typeof AuthenticatedStudiesIndexRoute
  '/diseases/': typeof ProtectedDiseasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedIndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/governance': typeof AuthenticatedGovernanceRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/participants': typeof AuthenticatedParticipantsRoute
  '/quantum-lab': typeof AuthenticatedQuantumLabRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/about': typeof ProtectedAboutRoute
  '/genomics': typeof ProtectedGenomicsRoute
  '/platform': typeof ProtectedPlatformRoute
  '/research': typeof ProtectedResearchRoute
  '/security': typeof ProtectedSecurityRoute
  '/candidates/$candidateId': typeof AuthenticatedCandidatesCandidateIdRoute
  '/studies/$studyId': typeof AuthenticatedStudiesStudyIdRoute
  '/diseases/$slug': typeof ProtectedDiseasesSlugRoute
  '/studies': typeof AuthenticatedStudiesIndexRoute
  '/diseases': typeof ProtectedDiseasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/governance': typeof AuthenticatedGovernanceRoute
  '/_authenticated/operations': typeof AuthenticatedOperationsRoute
  '/_authenticated/participants': typeof AuthenticatedParticipantsRoute
  '/_authenticated/quantum-lab': typeof AuthenticatedQuantumLabRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_protected/about': typeof ProtectedAboutRoute
  '/_protected/genomics': typeof ProtectedGenomicsRoute
  '/_protected/platform': typeof ProtectedPlatformRoute
  '/_protected/research': typeof ProtectedResearchRoute
  '/_protected/security': typeof ProtectedSecurityRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_authenticated/candidates/$candidateId': typeof AuthenticatedCandidatesCandidateIdRoute
  '/_authenticated/studies/$studyId': typeof AuthenticatedStudiesStudyIdRoute
  '/_protected/diseases/$slug': typeof ProtectedDiseasesSlugRoute
  '/_authenticated/studies/': typeof AuthenticatedStudiesIndexRoute
  '/_protected/diseases/': typeof ProtectedDiseasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/governance'
    | '/operations'
    | '/participants'
    | '/quantum-lab'
    | '/tasks'
    | '/about'
    | '/genomics'
    | '/platform'
    | '/research'
    | '/security'
    | '/candidates/$candidateId'
    | '/studies/$studyId'
    | '/diseases/$slug'
    | '/studies/'
    | '/diseases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/governance'
    | '/operations'
    | '/participants'
    | '/quantum-lab'
    | '/tasks'
    | '/about'
    | '/genomics'
    | '/platform'
    | '/research'
    | '/security'
    | '/candidates/$candidateId'
    | '/studies/$studyId'
    | '/diseases/$slug'
    | '/studies'
    | '/diseases'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/governance'
    | '/_authenticated/operations'
    | '/_authenticated/participants'
    | '/_authenticated/quantum-lab'
    | '/_authenticated/tasks'
    | '/_protected/about'
    | '/_protected/genomics'
    | '/_protected/platform'
    | '/_protected/research'
    | '/_protected/security'
    | '/_protected/'
    | '/_authenticated/candidates/$candidateId'
    | '/_authenticated/studies/$studyId'
    | '/_protected/diseases/$slug'
    | '/_authenticated/studies/'
    | '/_protected/diseases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ProtectedAboutRoute: typeof ProtectedAboutRoute
  ProtectedGenomicsRoute: typeof ProtectedGenomicsRoute
  ProtectedPlatformRoute: typeof ProtectedPlatformRoute
  ProtectedResearchRoute: typeof ProtectedResearchRoute
  ProtectedSecurityRoute: typeof ProtectedSecurityRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedDiseasesSlugRoute: typeof ProtectedDiseasesSlugRoute
  ProtectedDiseasesIndexRoute: typeof ProtectedDiseasesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/governance': {
      id: '/_authenticated/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof AuthenticatedGovernanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operations': {
      id: '/_authenticated/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthenticatedOperationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/participants': {
      id: '/_authenticated/participants'
      path: '/participants'
      fullPath: '/participants'
      preLoaderRoute: typeof AuthenticatedParticipantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quantum-lab': {
      id: '/_authenticated/quantum-lab'
      path: '/quantum-lab'
      fullPath: '/quantum-lab'
      preLoaderRoute: typeof AuthenticatedQuantumLabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/about': {
      id: '/_protected/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof ProtectedAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/genomics': {
      id: '/_protected/genomics'
      path: '/genomics'
      fullPath: '/genomics'
      preLoaderRoute: typeof ProtectedGenomicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/platform': {
      id: '/_protected/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof ProtectedPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/research': {
      id: '/_protected/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ProtectedResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/security': {
      id: '/_protected/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof ProtectedSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/candidates/$candidateId': {
      id: '/_authenticated/candidates/$candidateId'
      path: '/candidates/$candidateId'
      fullPath: '/candidates/$candidateId'
      preLoaderRoute: typeof AuthenticatedCandidatesCandidateIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studies/': {
      id: '/_authenticated/studies/'
      path: '/studies'
      fullPath: '/studies/'
      preLoaderRoute: typeof AuthenticatedStudiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studies/$studyId': {
      id: '/_authenticated/studies/$studyId'
      path: '/studies/$studyId'
      fullPath: '/studies/$studyId'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_protected/diseases/': {
      id: '/_protected/diseases/'
      path: '/diseases'
      fullPath: '/diseases/'
      preLoaderRoute: typeof ProtectedDiseasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/diseases/$slug': {
      id: '/_protected/diseases/$slug'
      path: '/diseases/$slug'
      fullPath: '/diseases/$slug'
      preLoaderRoute: typeof ProtectedDiseasesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGovernanceRoute: typeof AuthenticatedGovernanceRoute
  AuthenticatedOperationsRoute: typeof AuthenticatedOperationsRoute
  AuthenticatedParticipantsRoute: typeof AuthenticatedParticipantsRoute
  AuthenticatedQuantumLabRoute: typeof AuthenticatedQuantumLabRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedCandidatesCandidateIdRoute: typeof AuthenticatedCandidatesCandidateIdRoute
  AuthenticatedStudiesStudyIdRoute: typeof AuthenticatedStudiesStudyIdRoute
  AuthenticatedStudiesIndexRoute: typeof AuthenticatedStudiesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGovernanceRoute: AuthenticatedGovernanceRoute,
  AuthenticatedOperationsRoute: AuthenticatedOperationsRoute,
  AuthenticatedParticipantsRoute: AuthenticatedParticipantsRoute,
  AuthenticatedQuantumLabRoute: AuthenticatedQuantumLabRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedCandidatesCandidateIdRoute:
    AuthenticatedCandidatesCandidateIdRoute,
  AuthenticatedStudiesStudyIdRoute: AuthenticatedStudiesStudyIdRoute,
  AuthenticatedStudiesIndexRoute: AuthenticatedStudiesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ProtectedAboutRoute: ProtectedAboutRoute,
  ProtectedGenomicsRoute: ProtectedGenomicsRoute,
  ProtectedPlatformRoute: ProtectedPlatformRoute,
  ProtectedResearchRoute: ProtectedResearchRoute,
  ProtectedSecurityRoute: ProtectedSecurityRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedDiseasesSlugRoute: ProtectedDiseasesSlugRoute,
  ProtectedDiseasesIndexRoute: ProtectedDiseasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
