/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedGenomicsRouteImport } from './routes/_authenticated/genomics'
import { Route as AuthenticatedGovernanceRouteImport } from './routes/_authenticated/governance'
import { Route as AuthenticatedOperationsRouteImport } from './routes/_authenticated/operations'
import { Route as AuthenticatedParticipantsRouteImport } from './routes/_authenticated/participants'
import { Route as AuthenticatedQuantumLabRouteImport } from './routes/_authenticated/quantum-lab'
import { Route as AuthenticatedResearchRouteImport } from './routes/_authenticated/research'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as ProtectedAboutRouteImport } from './routes/_protected/about'
import { Route as ProtectedPlatformRouteImport } from './routes/_protected/platform'
import { Route as ProtectedSecurityRouteImport } from './routes/_protected/security'
import { Route as AuthenticatedCandidatesCandidateIdRouteImport } from './routes/_authenticated/candidates.$candidateId'
import { Route as AuthenticatedDiseasesIndexRouteImport } from './routes/_authenticated/diseases.index'
import { Route as AuthenticatedDiseasesSlugRouteImport } from './routes/_authenticated/diseases.$slug'
import { Route as AuthenticatedStudiesIndexRouteImport } from './routes/_authenticated/studies.index'
import { Route as AuthenticatedStudiesStudyIdRouteImport } from './routes/_authenticated/studies.$studyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGenomicsRoute = AuthenticatedGenomicsRouteImport.update({
  id: '/genomics',
  path: '/genomics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGovernanceRoute = AuthenticatedGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperationsRoute = AuthenticatedOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParticipantsRoute =
  AuthenticatedParticipantsRouteImport.update({
    id: '/participants',
    path: '/participants',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuantumLabRoute = AuthenticatedQuantumLabRouteImport.update({
  id: '/quantum-lab',
  path: '/quantum-lab',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResearchRoute = AuthenticatedResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ProtectedAboutRoute = ProtectedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedPlatformRoute = ProtectedPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSecurityRoute = ProtectedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const AuthenticatedCandidatesCandidateIdRoute =
  AuthenticatedCandidatesCandidateIdRouteImport.update({
    id: '/candidates/$candidateId',
    path: '/candidates/$candidateId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiseasesIndexRoute =
  AuthenticatedDiseasesIndexRouteImport.update({
    id: '/diseases/',
    path: '/diseases/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiseasesSlugRoute =
  AuthenticatedDiseasesSlugRouteImport.update({
    id: '/diseases/$slug',
    path: '/diseases/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudiesIndexRoute =
  AuthenticatedStudiesIndexRouteImport.update({
    id: '/studies/',
    path: '/studies/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudiesStudyIdRoute =
  AuthenticatedStudiesStudyIdRouteImport.update({
    id: '/studies/$studyId',
    path: '/studies/$studyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/genomics': typeof AuthenticatedGenomicsRoute
  '/governance': typeof AuthenticatedGovernanceRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/participants': typeof AuthenticatedParticipantsRoute
  '/quantum-lab': typeof AuthenticatedQuantumLabRoute
  '/research': typeof AuthenticatedResearchRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/about': typeof ProtectedAboutRoute
  '/platform': typeof ProtectedPlatformRoute
  '/security': typeof ProtectedSecurityRoute
  '/candidates/$candidateId': typeof AuthenticatedCandidatesCandidateIdRoute
  '/diseases/$slug': typeof AuthenticatedDiseasesSlugRoute
  '/studies/$studyId': typeof AuthenticatedStudiesStudyIdRoute
  '/diseases/': typeof AuthenticatedDiseasesIndexRoute
  '/studies/': typeof AuthenticatedStudiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/genomics': typeof AuthenticatedGenomicsRoute
  '/governance': typeof AuthenticatedGovernanceRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/participants': typeof AuthenticatedParticipantsRoute
  '/quantum-lab': typeof AuthenticatedQuantumLabRoute
  '/research': typeof AuthenticatedResearchRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/about': typeof ProtectedAboutRoute
  '/platform': typeof ProtectedPlatformRoute
  '/security': typeof ProtectedSecurityRoute
  '/candidates/$candidateId': typeof AuthenticatedCandidatesCandidateIdRoute
  '/diseases/$slug': typeof AuthenticatedDiseasesSlugRoute
  '/studies/$studyId': typeof AuthenticatedStudiesStudyIdRoute
  '/diseases': typeof AuthenticatedDiseasesIndexRoute
  '/studies': typeof AuthenticatedStudiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/genomics': typeof AuthenticatedGenomicsRoute
  '/_authenticated/governance': typeof AuthenticatedGovernanceRoute
  '/_authenticated/operations': typeof AuthenticatedOperationsRoute
  '/_authenticated/participants': typeof AuthenticatedParticipantsRoute
  '/_authenticated/quantum-lab': typeof AuthenticatedQuantumLabRoute
  '/_authenticated/research': typeof AuthenticatedResearchRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_protected/about': typeof ProtectedAboutRoute
  '/_protected/platform': typeof ProtectedPlatformRoute
  '/_protected/security': typeof ProtectedSecurityRoute
  '/_authenticated/candidates/$candidateId': typeof AuthenticatedCandidatesCandidateIdRoute
  '/_authenticated/diseases/$slug': typeof AuthenticatedDiseasesSlugRoute
  '/_authenticated/studies/$studyId': typeof AuthenticatedStudiesStudyIdRoute
  '/_authenticated/diseases/': typeof AuthenticatedDiseasesIndexRoute
  '/_authenticated/studies/': typeof AuthenticatedStudiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/genomics'
    | '/governance'
    | '/operations'
    | '/participants'
    | '/quantum-lab'
    | '/research'
    | '/tasks'
    | '/about'
    | '/platform'
    | '/security'
    | '/candidates/$candidateId'
    | '/diseases/$slug'
    | '/studies/$studyId'
    | '/diseases/'
    | '/studies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/genomics'
    | '/governance'
    | '/operations'
    | '/participants'
    | '/quantum-lab'
    | '/research'
    | '/tasks'
    | '/about'
    | '/platform'
    | '/security'
    | '/candidates/$candidateId'
    | '/diseases/$slug'
    | '/studies/$studyId'
    | '/diseases'
    | '/studies'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_protected'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/genomics'
    | '/_authenticated/governance'
    | '/_authenticated/operations'
    | '/_authenticated/participants'
    | '/_authenticated/quantum-lab'
    | '/_authenticated/research'
    | '/_authenticated/tasks'
    | '/_protected/about'
    | '/_protected/platform'
    | '/_protected/security'
    | '/_authenticated/candidates/$candidateId'
    | '/_authenticated/diseases/$slug'
    | '/_authenticated/studies/$studyId'
    | '/_authenticated/diseases/'
    | '/_authenticated/studies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/genomics': {
      id: '/_authenticated/genomics'
      path: '/genomics'
      fullPath: '/genomics'
      preLoaderRoute: typeof AuthenticatedGenomicsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/governance': {
      id: '/_authenticated/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof AuthenticatedGovernanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operations': {
      id: '/_authenticated/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthenticatedOperationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/participants': {
      id: '/_authenticated/participants'
      path: '/participants'
      fullPath: '/participants'
      preLoaderRoute: typeof AuthenticatedParticipantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quantum-lab': {
      id: '/_authenticated/quantum-lab'
      path: '/quantum-lab'
      fullPath: '/quantum-lab'
      preLoaderRoute: typeof AuthenticatedQuantumLabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/research': {
      id: '/_authenticated/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof AuthenticatedResearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_protected/about': {
      id: '/_protected/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof ProtectedAboutRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/platform': {
      id: '/_protected/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof ProtectedPlatformRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/security': {
      id: '/_protected/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof ProtectedSecurityRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_authenticated/candidates/$candidateId': {
      id: '/_authenticated/candidates/$candidateId'
      path: '/candidates/$candidateId'
      fullPath: '/candidates/$candidateId'
      preLoaderRoute: typeof AuthenticatedCandidatesCandidateIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diseases/': {
      id: '/_authenticated/diseases/'
      path: '/diseases'
      fullPath: '/diseases/'
      preLoaderRoute: typeof AuthenticatedDiseasesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diseases/$slug': {
      id: '/_authenticated/diseases/$slug'
      path: '/diseases/$slug'
      fullPath: '/diseases/$slug'
      preLoaderRoute: typeof AuthenticatedDiseasesSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studies/': {
      id: '/_authenticated/studies/'
      path: '/studies'
      fullPath: '/studies/'
      preLoaderRoute: typeof AuthenticatedStudiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studies/$studyId': {
      id: '/_authenticated/studies/$studyId'
      path: '/studies/$studyId'
      fullPath: '/studies/$studyId'
      preLoaderRoute: typeof AuthenticatedStudiesStudyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGenomicsRoute: typeof AuthenticatedGenomicsRoute
  AuthenticatedGovernanceRoute: typeof AuthenticatedGovernanceRoute
  AuthenticatedOperationsRoute: typeof AuthenticatedOperationsRoute
  AuthenticatedParticipantsRoute: typeof AuthenticatedParticipantsRoute
  AuthenticatedQuantumLabRoute: typeof AuthenticatedQuantumLabRoute
  AuthenticatedResearchRoute: typeof AuthenticatedResearchRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedCandidatesCandidateIdRoute: typeof AuthenticatedCandidatesCandidateIdRoute
  AuthenticatedDiseasesSlugRoute: typeof AuthenticatedDiseasesSlugRoute
  AuthenticatedStudiesStudyIdRoute: typeof AuthenticatedStudiesStudyIdRoute
  AuthenticatedDiseasesIndexRoute: typeof AuthenticatedDiseasesIndexRoute
  AuthenticatedStudiesIndexRoute: typeof AuthenticatedStudiesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGenomicsRoute: AuthenticatedGenomicsRoute,
  AuthenticatedGovernanceRoute: AuthenticatedGovernanceRoute,
  AuthenticatedOperationsRoute: AuthenticatedOperationsRoute,
  AuthenticatedParticipantsRoute: AuthenticatedParticipantsRoute,
  AuthenticatedQuantumLabRoute: AuthenticatedQuantumLabRoute,
  AuthenticatedResearchRoute: AuthenticatedResearchRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedCandidatesCandidateIdRoute:
    AuthenticatedCandidatesCandidateIdRoute,
  AuthenticatedDiseasesSlugRoute: AuthenticatedDiseasesSlugRoute,
  AuthenticatedStudiesStudyIdRoute: AuthenticatedStudiesStudyIdRoute,
  AuthenticatedDiseasesIndexRoute: AuthenticatedDiseasesIndexRoute,
  AuthenticatedStudiesIndexRoute: AuthenticatedStudiesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ProtectedRouteRouteChildren {
  ProtectedAboutRoute: typeof ProtectedAboutRoute
  ProtectedPlatformRoute: typeof ProtectedPlatformRoute
  ProtectedSecurityRoute: typeof ProtectedSecurityRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedAboutRoute: ProtectedAboutRoute,
  ProtectedPlatformRoute: ProtectedPlatformRoute,
  ProtectedSecurityRoute: ProtectedSecurityRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
